import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Copy, Flag, Globe2, Timer, Trophy, Users } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import type { Json } from '@/integrations/supabase/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import CountryPractice from './CountryPractice';

const CATEGORY_OPTIONS = ['Boy name','Girl name','Food','Fruit','Country','Capital','Town/City','Car','Animal','Plant','Profession','Celebrity','Sport','Brand','Object'];
const LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
type Settings = { duration:number; rounds:number; categories:string[]; allowCapitalCityDuplicate:boolean };
type ChallengeVote = 'valid'|'invalid'|'shared'|boolean;
type Challenge = { id:string; playerId:string; category:string; challengerId:string; votes:Record<string,ChallengeVote>; resolved?:boolean; valid?:boolean; shared?:boolean };
type State = { round:number; letter:string; letterPending?:boolean; usedLetters:string[]; answers:Record<string,Record<string,string>>; submitted:string[]; scores:Record<string,Record<string,number>>; totals:Record<string,number>; roundScores:Record<string,number[]>; challenges:Challenge[]; roundEndsAt:string|null };
type Room = { id:string; room_code:string; host_id:string; player_ids:string[]; player_names:string[]; status:'lobby'|'answering'|'review'|'finished'; settings:Settings; game_state:State };

const emptyState = ():State => ({round:0,letter:'',letterPending:false,usedLetters:[],answers:{},submitted:[],scores:{},totals:{},roundScores:{},challenges:[],roundEndsAt:null});
const randomCode = () => String(Math.floor(10000+Math.random()*90000));
const normalize = (value:string) => value.trim().toLocaleLowerCase();
const hydrate = (raw:unknown):Room => {
  const row=raw as Room;
  return {...row,settings:row.settings as Settings,game_state:{...emptyState(),...(row.game_state as State),usedLetters:row.game_state?.usedLetters??[],roundScores:row.game_state?.roundScores??{}}};
};
const scoreAnswers = (room:Room) => {
  const scores:Record<string,Record<string,number>>={};
  room.player_ids.forEach(id=>{scores[id]={};});
  room.settings.categories.forEach(category=>{
    const counts=new Map<string,number>();
    room.player_ids.forEach(id=>{const value=normalize(room.game_state.answers[id]?.[category]??'');const invalid=room.game_state.challenges.some(c=>c.playerId===id&&c.category===category&&c.resolved&&c.valid===false);if(value&&value.startsWith(room.game_state.letter.toLowerCase())&&!invalid)counts.set(value,(counts.get(value)??0)+1);});
    room.player_ids.forEach(id=>{const value=normalize(room.game_state.answers[id]?.[category]??'');const challenge=room.game_state.challenges.find(c=>c.playerId===id&&c.category===category&&c.resolved);scores[id][category]=challenge?.shared?5:value&&value.startsWith(room.game_state.letter.toLowerCase())&&challenge?.valid!==false?(counts.get(value)===1?10:5):0;});
  });
  if(!room.settings.allowCapitalCityDuplicate&&room.settings.categories.includes('Capital')&&room.settings.categories.includes('Town/City'))room.player_ids.forEach(id=>{if(normalize(room.game_state.answers[id]?.Capital??'')&&normalize(room.game_state.answers[id]?.Capital??'')===normalize(room.game_state.answers[id]?.['Town/City']??''))scores[id]['Town/City']=0;});
  return scores;
};

const CountryGame=()=>{
  const [room,setRoom]=useState<Room|null>(null);
  const [playerId,setPlayerId]=useState('');
  const [mode,setMode]=useState<'game-mode'|'select'|'practice'|'host'|'join'>('game-mode');
  const [name,setName]=useState('');const [code,setCode]=useState('');
  const [answers,setAnswers]=useState<Record<string,string>>({});
  const [onlineIds,setOnlineIds]=useState<string[]>([]);const [connecting,setConnecting]=useState(false);const [,tick]=useState(0);
  const [shuffleDone,setShuffleDone]=useState(false);const [displayLetter,setDisplayLetter]=useState('?');
  const timeoutRound=useRef(0);
  const [draft]=useState<Settings>({duration:90,rounds:5,categories:CATEGORY_OPTIONS.slice(0,6),allowCapitalCityDuplicate:false});
  const isHost=!!room&&room.host_id===playerId;
  const remaining=room?.game_state.roundEndsAt?Math.max(0,Math.ceil((new Date(room.game_state.roundEndsAt).getTime()-Date.now())/1000)):0;

  const update=async(values:Partial<Room>)=>{if(!room)return;if(values.settings&&room.game_state.round>0)return toast.info('Match settings are locked until a new match.');setRoom(previous=>previous?{...previous,...values}:previous);const {error}=await supabase.from('country_rooms').update({...(values.settings?{settings:values.settings as unknown as Json}:{}),...(values.game_state?{game_state:values.game_state as unknown as Json}:{}),...(values.status?{status:values.status}:{}),updated_at:new Date().toISOString()}).eq('id',room.id);if(error)toast.error(error.message);};
  const ensurePlayerId=async()=>{if(playerId)return playerId;const {data:session}=await supabase.auth.getSession();if(session.session?.user.id){setPlayerId(session.session.user.id);return session.session.user.id;}const {data,error}=await supabase.auth.signInAnonymously();if(error)throw new Error(`Anonymous sign-in failed: ${error.message}`);if(!data.user)throw new Error('Could not create a player identity');setPlayerId(data.user.id);return data.user.id;};

  useEffect(()=>{void ensurePlayerId();},[]);
  useEffect(()=>{document.body.classList.add('country-page');return()=>document.body.classList.remove('country-page');},[]);
  useEffect(()=>{const timer=window.setInterval(()=>tick(x=>x+1),500);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!room||!playerId)return;const channel=supabase.channel(`country-${room.id}`,{config:{presence:{key:playerId}}}).on('postgres_changes',{event:'*',schema:'public',table:'country_rooms',filter:`id=eq.${room.id}`},payload=>payload.eventType==='DELETE'?setRoom(null):setRoom(hydrate(payload.new))).on('presence',{event:'sync'},()=>setOnlineIds(Object.keys(channel.presenceState()))).subscribe(status=>{if(status==='SUBSCRIBED')void channel.track({playerId});});const poll=window.setInterval(async()=>{const {data}=await supabase.from('country_rooms').select().eq('id',room.id).maybeSingle();if(data)setRoom(hydrate(data));},1500);return()=>{clearInterval(poll);void channel.untrack();void supabase.removeChannel(channel);};},[room?.id,playerId]);
  useEffect(()=>{setAnswers({});timeoutRound.current=0;},[room?.game_state.round]);
  useEffect(()=>{if(!room?.game_state.letterPending)return;setShuffleDone(false);let count=0;const spin=window.setInterval(()=>{setDisplayLetter(LETTERS[Math.floor(Math.random()*LETTERS.length)]);count+=1;if(count>=20){clearInterval(spin);setDisplayLetter(room.game_state.letter);setShuffleDone(true);}},100);return()=>clearInterval(spin);},[room?.game_state.letter,room?.game_state.letterPending]);

  const create=async()=>{if(!name.trim())return toast.error('Enter your name');setConnecting(true);try{const id=await ensurePlayerId();let created:unknown=null;let message='Room creation failed';for(let i=0;i<5;i++){const {data,error}=await supabase.from('country_rooms').insert({room_code:randomCode(),host_id:id,player_ids:[id],player_names:[name.trim()],settings:draft as unknown as Json,game_state:emptyState() as unknown as Json}).select().single();if(data&&!error){created=data;break;}message=error?.message??message;if(error?.code!=='23505')break;}if(!created)throw new Error(message);setRoom(hydrate(created));}catch(error){toast.error(error instanceof Error?error.message:'Could not create room');}finally{setConnecting(false);}};
  const join=async()=>{if(!name.trim()||code.length!==5)return toast.error('Enter your name and a 5-digit code');setConnecting(true);try{await ensurePlayerId();const {data,error}=await supabase.rpc('join_country_room',{join_code:code,player_name:name.trim()});if(error)throw error;if(!data?.length)throw new Error('Room not found or full');setRoom(hydrate(data[0]));}catch(error){toast.error(error instanceof Error?error.message:'Could not join room');}finally{setConnecting(false);}};
  const leave=async()=>{if(room)await supabase.rpc('leave_country_room',{target_room_id:room.id});setRoom(null);setMode('select');setAnswers({});};
  const unusedLetter=(extra:string[]=[])=>(()=>{const used=[...(room?.game_state.usedLetters??[]),...extra];const available=LETTERS.filter(x=>!used.includes(x));return available[Math.floor(Math.random()*available.length)];})();
  const prepareRound=async(totals=room?.game_state.totals??{},roundScores=room?.game_state.roundScores??{})=>{if(!room||!isHost)return;const letter=unusedLetter();if(!letter)return toast.error('No unused letters remain');setAnswers({});await update({status:'lobby',game_state:{...emptyState(),round:room.game_state.round+1,letter,letterPending:true,usedLetters:room.game_state.usedLetters??[],totals,roundScores}});};
  const skipLetter=async()=>{if(!room||!isHost||!shuffleDone)return;const rejected=Array.from(new Set([...(room.game_state.usedLetters??[]),room.game_state.letter]));const letter=unusedLetter([room.game_state.letter]);if(!letter)return toast.error('No unused letters remain');await update({game_state:{...room.game_state,letter,usedLetters:rejected}});};
  const acceptLetter=async()=>{if(!room||!isHost||!shuffleDone)return;await update({status:'answering',game_state:{...room.game_state,letterPending:false,usedLetters:Array.from(new Set([...(room.game_state.usedLetters??[]),room.game_state.letter])),roundEndsAt:new Date(Date.now()+room.settings.duration*1000).toISOString()}});};
  const submit=async()=>{if(!room||room.game_state.submitted.includes(playerId))return;const {data,error}=await supabase.rpc('country_submit_answers',{target_room_id:room.id,player_answers:answers as unknown as Json});if(error){if(error.code==='PGRST202'||error.message.includes('country_submit_answers')){await update({game_state:{...room.game_state,answers:{...room.game_state.answers,[playerId]:answers},submitted:[...room.game_state.submitted,playerId]}});return;}toast.error(error.message);return;}if(data?.[0])setRoom(hydrate(data[0]));};
  const beginReview=async()=>{if(!room||!isHost)return;const latest=(await supabase.from('country_rooms').select().eq('id',room.id).single()).data;if(!latest)return;const current=hydrate(latest);await update({status:'review',game_state:{...current.game_state,scores:scoreAnswers(current),roundEndsAt:null}});};
  useEffect(()=>{if(room?.status!=='answering'||remaining!==0||!room.game_state.roundEndsAt||timeoutRound.current===room.game_state.round)return;timeoutRound.current=room.game_state.round;void submit();if(isHost)window.setTimeout(()=>void beginReview(),1200);},[remaining,room?.status,room?.game_state.round,answers,isHost]);

  const challenge=(targetId:string,category:string)=>{if(!room||!room.game_state.answers[targetId]?.[category])return;const exists=room.game_state.challenges.some(c=>c.playerId===targetId&&c.category===category);if(exists)return toast.info('That answer is already being challenged');const item:Challenge={id:crypto.randomUUID(),playerId:targetId,category,challengerId:playerId,votes:{}};void update({game_state:{...room.game_state,challenges:[...room.game_state.challenges,item]}});};
  const vote=async(id:string,choice:'valid'|'invalid'|'shared')=>{if(!room)return;await update({game_state:{...room.game_state,challenges:room.game_state.challenges.map(c=>c.id===id?{...c,votes:{...c.votes,[playerId]:choice}}:c)}});};
  const applyChallengeVotes=async(challenge:Challenge)=>{if(!isHost)return;const values=Object.values(challenge.votes);const counts={valid:values.filter(v=>v===true||v==='valid').length,invalid:values.filter(v=>v===false||v==='invalid').length,shared:values.filter(v=>v==='shared').length};const highest=Math.max(counts.valid,counts.invalid,counts.shared);if(highest===0)return toast.error('At least one player must vote first');const winners=(Object.keys(counts) as Array<'valid'|'invalid'|'shared'>).filter(key=>counts[key]===highest);if(winners.length!==1)return toast.error('The vote is tied. More players must vote before applying the verdict.');await resolve(challenge,winners[0]);};
  const resolve=async(challenge:Challenge,outcome:'valid'|'invalid'|'shared')=>{if(!room||!isHost)return;const challenges=room.game_state.challenges.map(c=>c.id===challenge.id?{...c,resolved:true,valid:outcome!=='invalid',shared:outcome==='shared'}:c);const next={...room,game_state:{...room.game_state,challenges}};await update({game_state:{...next.game_state,scores:scoreAnswers(next)}});};
  const completeReview=async(early=false)=>{if(!room||!isHost)return;if(room.game_state.challenges.some(c=>!c.resolved))return toast.error('Resolve every challenge first');const totals={...room.game_state.totals};const roundScores={...room.game_state.roundScores};room.player_ids.forEach(id=>{const score=Object.values(room.game_state.scores[id]??{}).reduce((a,b)=>a+b,0);totals[id]=(totals[id]??0)+score;roundScores[id]=[...(roundScores[id]??[]),score];});if(early||room.game_state.round>=room.settings.rounds)await update({status:'finished',game_state:{...room.game_state,totals,roundScores}});else await prepareRound(totals,roundScores);};
  const playerName=(id:string)=>room?.player_names[room.player_ids.indexOf(id)]??'Player';
  const leaderboard=useMemo(()=>room?[...room.player_ids].sort((a,b)=>(room.game_state.totals[b]??0)-(room.game_state.totals[a]??0)):[],[room]);
  const restartSameRoom=async()=>{if(!room||!isHost)return;setAnswers({});await update({status:'lobby',game_state:emptyState()});};
  const startNewRoom=async()=>{if(room)await supabase.rpc('leave_country_room',{target_room_id:room.id});setRoom(null);setAnswers({});setCode('');setMode('host');};
  const returnToCountryHome=async()=>{if(room)await supabase.rpc('leave_country_room',{target_room_id:room.id});setRoom(null);setAnswers({});setCode('');setMode('game-mode');};
  const toolbar=room?<div className="fixed left-4 top-4 z-[200] flex gap-2"><Button variant="outline" className="border-sky-300/50 bg-slate-900 text-sky-100" onClick={leave}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button><Button variant="destructive" onClick={leave}>Leave room</Button></div>:null;

  if(!room&&mode==='practice')return <CountryPractice onBack={()=>setMode('game-mode')}/>;

  if(!room)return <main className="country-page min-h-screen p-4 pt-20"><Link to="/" className="absolute left-5 top-5"><Button variant="outline" className="border-sky-300/50 text-sky-200"><ArrowLeft className="mr-2 h-4 w-4"/>Home</Button></Link><Card className="mx-auto max-w-lg border-sky-300/20 bg-slate-900/90 text-slate-100"><CardHeader><CardTitle className="text-center text-3xl text-gold"><Globe2 className="mr-2 inline"/>Country Game</CardTitle></CardHeader><CardContent className="space-y-4">{mode==='game-mode'?<><Button className="w-full bg-gradient-gold text-slate-950" onClick={()=>setMode('select')}>Multiplayer</Button><Button className="w-full border-sky-300/40 text-sky-100" variant="outline" onClick={()=>setMode('practice')}>Practice mode</Button></>:mode==='practice'?<><div className="rounded-xl border border-sky-300/20 bg-sky-950/40 p-8 text-center"><h2 className="text-2xl font-bold text-sky-200">Practice mode</h2><p>Coming soon.</p></div><Button variant="ghost" onClick={()=>setMode('game-mode')}>Back</Button></>:mode==='select'?<><Button className="w-full bg-gradient-gold text-slate-950" onClick={()=>setMode('host')}>Host a game</Button><Button className="w-full" variant="outline" onClick={()=>setMode('join')}>Join a game</Button><Button variant="ghost" onClick={()=>setMode('game-mode')}>Back</Button></>:<><Input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/>{mode==='join'&&<Input placeholder="5-digit room code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,5))}/>}<Button disabled={connecting} className="w-full bg-gradient-gold text-slate-950" onClick={mode==='host'?create:join}>{connecting?'Connecting…':mode==='host'?'Create room':'Join room'}</Button><Button variant="ghost" onClick={()=>setMode('select')}>Back</Button></>}</CardContent></Card></main>;
  if(room.status==='lobby'&&room.game_state.letterPending)return <main className="country-page flex min-h-screen items-center justify-center p-4">{toolbar}<Card className="w-full max-w-xl border-sky-300/30 bg-slate-900/95 text-center text-slate-100"><CardHeader><p className="font-bold uppercase tracking-[.25em] text-sky-300">Round {room.game_state.round} of {room.settings.rounds}</p><CardTitle className="text-3xl">Choosing a letter...</CardTitle></CardHeader><CardContent><div className={`country-letter-reveal mx-auto mb-6 flex h-44 w-44 items-center justify-center rounded-full border-4 border-sky-300/60 bg-sky-950 text-8xl font-black text-sky-300 ${shuffleDone?'is-settled':'is-shuffling'}`}>{displayLetter}</div>{isHost?<div className="flex justify-center gap-3"><Button disabled={!shuffleDone} variant="outline" onClick={skipLetter}>Skip letter</Button><Button disabled={!shuffleDone} className="bg-gradient-gold text-slate-950" onClick={acceptLetter}>Accept {room.game_state.letter}</Button></div>:<p>Waiting for the room leader to accept or skip the letter.</p>}</CardContent></Card></main>;
  if(room.status==='lobby')return <main className="country-page min-h-screen p-4 pt-20">{toolbar}<div className="mx-auto grid max-w-5xl gap-5 md:grid-cols-2"><Card className="country-card"><CardHeader><CardTitle className="text-gold">Room {room.room_code} <Button size="icon" variant="ghost" onClick={()=>navigator.clipboard.writeText(room.room_code)}><Copy className="h-4 w-4"/></Button></CardTitle></CardHeader><CardContent><p><Users className="mr-2 inline h-4 w-4"/>{room.player_names.length}/6 joined · {onlineIds.length||1} online</p>{room.player_names.map((n,i)=><p key={room.player_ids[i]} className="rounded p-2 odd:bg-sky-950/30">{n}{room.player_ids[i]===room.host_id?' · Leader':''}{onlineIds.length&&!onlineIds.includes(room.player_ids[i])?' · Offline':''}</p>)}</CardContent></Card><Card className="country-card"><CardHeader><CardTitle className="text-gold">Game setup</CardTitle></CardHeader><CardContent className="country-setup-grid"><label>Round time<select disabled={!isHost} value={room.settings.duration} onChange={e=>update({settings:{...room.settings,duration:Number(e.target.value)}})}>{[60,90,120,180,300].map(x=><option key={x}>{x}</option>)}</select></label><label>Rounds<Input disabled={!isHost} type="number" min={1} max={20} value={room.settings.rounds} onChange={e=>update({settings:{...room.settings,rounds:Math.max(1,Number(e.target.value))}})}/></label><div className="col-span-full"><p className="mb-2 font-bold text-sky-100">Categories ({room.settings.categories.length}/10)</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{CATEGORY_OPTIONS.map(cat=><label key={cat} className="country-category"><input disabled={!isHost} type="checkbox" checked={room.settings.categories.includes(cat)} onChange={e=>{const categories=e.target.checked?[...room.settings.categories,cat]:room.settings.categories.filter(x=>x!==cat);if(categories.length>=6&&categories.length<=10)void update({settings:{...room.settings,categories}});}}/>{cat}</label>)}</div></div>{room.settings.categories.includes('Capital')&&room.settings.categories.includes('Town/City')&&<label className="col-span-full country-category"><input disabled={!isHost} type="checkbox" checked={room.settings.allowCapitalCityDuplicate} onChange={e=>update({settings:{...room.settings,allowCapitalCityDuplicate:e.target.checked}})}/>Allow the same Capital and City answer</label>}{isHost&&<Button disabled={room.player_ids.length<2} onClick={()=>prepareRound()} className="col-span-full bg-gradient-gold text-slate-950">Start round 1</Button>}</CardContent></Card></div></main>;
  if(room.status==='answering')return <main className="country-page min-h-screen p-4 pt-20">{toolbar}<div className="mx-auto max-w-5xl"><div className="mb-5 flex justify-between"><div><p>Round {room.game_state.round}/{room.settings.rounds}</p><h1 className="text-5xl font-black text-gold">Letter {room.game_state.letter}</h1></div><div className="country-card rounded-xl p-4 text-2xl font-black text-sky-200"><Timer className="mr-2 inline"/>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</div></div><div className="overflow-hidden rounded-xl border border-sky-300/20 bg-slate-900/95"><table className="w-full"><thead><tr><th className="p-3 text-left">Category</th><th className="p-3 text-left">Your answer</th></tr></thead><tbody>{room.settings.categories.map(cat=><tr key={cat} className="border-t border-sky-300/15"><td className="p-3 font-bold text-sky-200">{cat}</td><td className="p-2"><Input disabled={remaining===0||room.game_state.submitted.includes(playerId)} value={answers[cat]??''} onChange={e=>setAnswers({...answers,[cat]:e.target.value})} placeholder={`${room.game_state.letter}…`}/></td></tr>)}</tbody></table></div><Button disabled={remaining===0||room.game_state.submitted.includes(playerId)} onClick={submit} className="mt-4 bg-gradient-gold text-slate-950">{room.game_state.submitted.includes(playerId)?'Submitted':'Submit answers'}</Button>{isHost&&<Button variant="outline" onClick={async()=>{await submit();window.setTimeout(()=>void beginReview(),500);}} className="ml-3 mt-4">End round now</Button>}</div></main>;
  if(room.status==='review')return <main className="country-page min-h-screen p-4 pt-20">{toolbar}<div className="mx-auto max-w-7xl"><h1 className="mb-5 text-3xl font-black text-gold">Review round {room.game_state.round}</h1><div className="overflow-auto rounded-xl border border-sky-300/20 bg-slate-900/95"><table className="min-w-full text-sm"><thead><tr><th className="p-3">Player</th>{room.settings.categories.map(c=><th key={c} className="p-3">{c}</th>)}<th>Total</th></tr></thead><tbody>{room.player_ids.map(id=><tr key={id} className="border-t border-sky-300/15"><th className="p-3 text-sky-200">{playerName(id)}</th>{room.settings.categories.map(cat=><td key={cat} className="min-w-40 p-2 text-center"><p>{room.game_state.answers[id]?.[cat]||'—'}</p><strong>{room.game_state.scores[id]?.[cat]??0} pts</strong>{room.game_state.answers[id]?.[cat]&&!room.game_state.challenges.some(c=>c.playerId===id&&c.category===cat)&&<button onClick={()=>challenge(id,cat)} className="ml-2 text-xs text-red-300 underline">Challenge</button>}</td>)}<td className="font-black">{Object.values(room.game_state.scores[id]??{}).reduce((a,b)=>a+b,0)}</td></tr>)}</tbody></table></div><div className="mt-5 space-y-3">{room.game_state.challenges.map(c=>{const values=Object.values(c.votes);const validVotes=values.filter(v=>v===true||v==='valid').length;const invalidVotes=values.filter(v=>v===false||v==='invalid').length;const sharedVotes=values.filter(v=>v==='shared').length;return <Card key={c.id} className="country-card"><CardContent className="flex flex-wrap items-center gap-3 p-4"><Flag className="text-red-400"/><span className="flex-1">Is <b>{room.game_state.answers[c.playerId]?.[c.category]}</b> valid for {c.category}?<small className="block">Votes: {validVotes} valid · {invalidVotes} invalid · {sharedVotes} same answer/tie</small></span>{c.resolved?<b>{c.shared?'Same answer — 5 points':c.valid?'Accepted':'Rejected'}</b>:<><Button size="sm" onClick={()=>vote(c.id,'valid')}>Valid</Button><Button size="sm" variant="destructive" onClick={()=>vote(c.id,'invalid')}>Invalid</Button><Button size="sm" variant="outline" onClick={()=>vote(c.id,'shared')}>Same answer / tie (5 pts)</Button>{isHost&&<Button size="sm" onClick={()=>applyChallengeVotes(c)}>Apply votes</Button>}</>}</CardContent></Card>;})}</div>{isHost&&<div className="mt-5 flex gap-3"><Button onClick={()=>completeReview()} className="bg-gradient-gold text-slate-950">{room.game_state.round>=room.settings.rounds?'Show final results':`Go to round ${room.game_state.round+1}`}</Button><Button variant="outline" onClick={()=>completeReview(true)}>End game early</Button></div>}</div></main>;
  return <main className="country-page min-h-screen p-4 pt-20">{toolbar}<Card className="country-card mx-auto max-w-4xl"><CardHeader><CardTitle className="text-center text-4xl text-gold"><Trophy className="mr-2 inline"/>Final leaderboard</CardTitle></CardHeader><CardContent><div className="overflow-auto"><table className="w-full"><thead><tr><th className="p-3 text-left">Place</th><th className="p-3 text-left">Player</th>{Array.from({length:room.game_state.round},(_,i)=><th key={i} className="p-3">Round {i+1}</th>)}<th className="p-3">Total</th></tr></thead><tbody>{leaderboard.map((id,i)=><tr key={id} className="border-t border-sky-300/20"><td className="p-3">{i+1}</td><td className="p-3 font-bold">{playerName(id)}</td>{Array.from({length:room.game_state.round},(_,r)=><td key={r} className="p-3 text-center">{room.game_state.roundScores[id]?.[r]??0}</td>)}<td className="p-3 text-center font-black text-sky-200">{room.game_state.totals[id]??0}</td></tr>)}</tbody></table></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{isHost?<Button className="bg-gradient-gold text-slate-950" onClick={restartSameRoom}>Restart in same room</Button>:<Button disabled variant="outline">Waiting for host to restart</Button>}<Button variant="outline" className="border-sky-300/50 text-sky-100" onClick={startNewRoom}>Start new game</Button><Button variant="outline" className="border-sky-300/50 text-sky-100" onClick={returnToCountryHome}>Country Game home</Button></div></CardContent></Card></main>;
};
export default CountryGame;
