// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuhdnatswszypzprtdar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1aGRuYXRzd3N6eXB6cHJ0ZGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMzYyNDQsImV4cCI6MjA3MzkxMjI0NH0.lvaRwWEHYjzvbReFujGwx01PeTTzKKK12Bogj7CqxVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});